// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/account" | "/account/orders/[publicId]" | "/admin" | "/admin/addons" | "/admin/analytics" | "/admin/catalog/characters" | "/admin/catalog/characters/[id]" | "/admin/catalog/characters/new" | "/admin/customers" | "/admin/login" | "/admin/media" | "/admin/notifications" | "/admin/orders" | "/admin/settings" | "/admin/show-programs" | "/admin/show-programs/[id]" | "/admin/show-programs/new" | "/admin/taxonomy" | "/admin/visitors" | "/catalog" | "/character/[slug]" | "/contacts" | "/login" | "/o-nas" | "/party-builder" | "/prices" | "/register" | "/show-programs" | "/show-programs/[slug]"
type AppRouteHandlerRoutes = "/api/account" | "/api/account/orders/[publicId]" | "/api/address/resolve" | "/api/address/suggest" | "/api/admin/dashboard" | "/api/admin/entities" | "/api/admin/entities/[id]" | "/api/admin/entities/[id]/crop" | "/api/admin/login" | "/api/admin/logout" | "/api/admin/media/upload" | "/api/admin/section/[section]" | "/api/auth/logout" | "/api/auth/send-code" | "/api/auth/verify-code" | "/api/availability" | "/api/csrf" | "/api/orders"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = "/api/legacy/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/account": {}
  "/account/orders/[publicId]": { "publicId": string; }
  "/admin": {}
  "/admin/addons": {}
  "/admin/analytics": {}
  "/admin/catalog/characters": {}
  "/admin/catalog/characters/[id]": { "id": string; }
  "/admin/catalog/characters/new": {}
  "/admin/customers": {}
  "/admin/login": {}
  "/admin/media": {}
  "/admin/notifications": {}
  "/admin/orders": {}
  "/admin/settings": {}
  "/admin/show-programs": {}
  "/admin/show-programs/[id]": { "id": string; }
  "/admin/show-programs/new": {}
  "/admin/taxonomy": {}
  "/admin/visitors": {}
  "/api/account": {}
  "/api/account/orders/[publicId]": { "publicId": string; }
  "/api/address/resolve": {}
  "/api/address/suggest": {}
  "/api/admin/dashboard": {}
  "/api/admin/entities": {}
  "/api/admin/entities/[id]": { "id": string; }
  "/api/admin/entities/[id]/crop": { "id": string; }
  "/api/admin/login": {}
  "/api/admin/logout": {}
  "/api/admin/media/upload": {}
  "/api/admin/section/[section]": { "section": string; }
  "/api/auth/logout": {}
  "/api/auth/send-code": {}
  "/api/auth/verify-code": {}
  "/api/availability": {}
  "/api/csrf": {}
  "/api/legacy/[[...path]]": { "path"?: string[]; }
  "/api/orders": {}
  "/catalog": {}
  "/character/[slug]": { "slug": string; }
  "/contacts": {}
  "/login": {}
  "/o-nas": {}
  "/party-builder": {}
  "/prices": {}
  "/register": {}
  "/show-programs": {}
  "/show-programs/[slug]": { "slug": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
