var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1v9fm0k._.js")
R.c("server/chunks/ssr/src_1sju0ca._.js")
R.c("server/chunks/ssr/src_0-rn4hu._.js")
R.c("server/chunks/ssr/16jy_next_dist_esm_build_templates_app-page_0ipl7x5.js")
R.c("server/chunks/ssr/[root-of-the-server]__1_4o8ax._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ev5rv-._.js")
R.c("server/chunks/ssr/_03yb5ax._.js")
R.c("server/chunks/ssr/node_modules__pnpm_0wufy-u._.js")
R.c("server/chunks/ssr/src_app_error_tsx_15dgtgq._.js")
R.c("server/chunks/ssr/src_app_loading_tsx_01g_-m0._.js")
R.c("server/chunks/ssr/src_app_not-found_tsx_1863-sq._.js")
R.c("server/chunks/ssr/16jy_next_dist_client_components_1yv9dj_._.js")
R.c("server/chunks/ssr/16jy_next_dist_client_components_builtin_unauthorized_1sws4ye.js")
R.c("server/chunks/ssr/16jy_next_dist_client_components_builtin_global-error_02b3qop.js")
R.c("server/chunks/ssr/_next-internal_server_app_page_actions_0hhsz1j.js")
R.m(65605)
module.exports=R.m(65605).exports
